development:
  adapter: postgresql
  #encoding: unicode
  database: ffodds
  pool: 2
  username: ffodds
  #password: 

production:
  adapter: postgresql
  #encoding: unicode
  database: ffodds
  pool: 2
  username: ffodds
  password: ffodds
